services:
  app:
    image: node:lts
    tty: true
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /app
    #restart: always
    volumes:
      - ./src:/app
    ports:
      - '3002:3000'
    command: sh -c "npm install && npm update && npm run dev"